### ISSUE TITLE
No "export" attribute for "Torrents" object

### ISSUE THREAD

**Issue by sotiris-bos** [rmartin16/qbittorrent-api#261]
### Describe the bug

Hello, I am trying to export torrents through the Python api client to no avail. I am getting the error:

```
python3 .scripts/qbit_final.py.test
Traceback (most recent call last):
  File "/root/.scripts/qbit_final.py.test", line 36, in <module>
    qbt_client.torrents.export(torrent_hashes={torrent.hash}, location='/config/.')
AttributeError: 'Torrents' object has no attribute 'export'
```

Am I doing something wrong or does this attribute not exist?

```
>> print(dir(qbittorrentapi.Client))
['_SID', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get', '_get_data', '_get_headers', '_get_requests_kwargs', '_handle_error_responses', '_initialize_context', '_initialize_lesser', '_list2string', '_normalize_torrent_files', '_post', '_request', '_request_manager', '_session', '_trigger_session_initialization', '_trim_known_kwargs', '_verbose_logging', 'app', 'app_buildInfo', 'app_build_info', 'app_defaultSavePath', 'app_default_save_path', 'app_preferences', 'app_setPreferences', 'app_set_preferences', 'app_shutdown', 'app_version', 'app_web_api_version', 'app_webapiVersion', 'application', 'auth', 'auth_log_in', 'auth_log_out', 'authorization', 'is_logged_in', 'log', 'log_main', 'log_peers', 'rss', 'rss_addFeed', 'rss_addFolder', 'rss_add_feed', 'rss_add_folder', 'rss_items', 'rss_markAsRead', 'rss_mark_as_read', 'rss_matchingArticles', 'rss_matching_articles', 'rss_moveItem', 'rss_move_item', 'rss_refreshItem', 'rss_refresh_item', 'rss_removeItem', 'rss_removeRule', 'rss_remove_item', 'rss_remove_rule', 'rss_renameRule', 'rss_rename_rule', 'rss_rules', 'rss_setRule', 'rss_set_rule', 'search', 'search_categories', 'search_delete', 'search_enablePlugin', 'search_enable_plugin', 'search_installPlugin', 'search_install_plugin', 'search_plugins', 'search_results', 'search_start', 'search_status', 'search_stop', 'search_uninstallPlugin', 'search_uninstall_plugin', 'search_updatePlugins', 'search_update_plugins', 'sync', 'sync_maindata', 'sync_torrentPeers', 'sync_torrent_peers', 'torrent_categories', 'torrent_tags', 'torrents', 'torrents_add', 'torrents_addPeers', 'torrents_addTags', 'torrents_addTrackers', 'torrents_add_peers', 'torrents_add_tags', 'torrents_add_trackers', 'torrents_bottomPrio', 'torrents_bottom_priority', 'torrents_categories', 'torrents_createCategory', 'torrents_createTags', 'torrents_create_category', 'torrents_create_tags', 'torrents_decreasePrio', 'torrents_decrease_priority', 'torrents_delete', 'torrents_deleteTags', 'torrents_delete_tags', 'torrents_downloadLimit', 'torrents_download_limit', 'torrents_editCategory', 'torrents_editTracker', 'torrents_edit_category', 'torrents_edit_tracker', 'torrents_filePrio', 'torrents_file_priority', 'torrents_files', 'torrents_increasePrio', 'torrents_increase_priority', 'torrents_info', 'torrents_pause', 'torrents_pieceHashes', 'torrents_pieceStates', 'torrents_piece_hashes', 'torrents_piece_states', 'torrents_properties', 'torrents_reannounce', 'torrents_recheck', 'torrents_removeCategories', 'torrents_removeTags', 'torrents_removeTrackers', 'torrents_remove_categories', 'torrents_remove_tags', 'torrents_remove_trackers', 'torrents_rename', 'torrents_renameFile', 'torrents_renameFolder', 'torrents_rename_file', 'torrents_rename_folder', 'torrents_resume', 'torrents_setAutoManagement', 'torrents_setCategory', 'torrents_setDownloadLimit', 'torrents_setDownloadPath', 'torrents_setForceStart', 'torrents_setLocation', 'torrents_setSavePath', 'torrents_setShareLimits', 'torrents_setSuperSeeding', 'torrents_setUploadLimit', 'torrents_set_auto_management', 'torrents_set_category', 'torrents_set_download_limit', 'torrents_set_download_path', 'torrents_set_force_start', 'torrents_set_location', 'torrents_set_save_path', 'torrents_set_share_limits', 'torrents_set_super_seeding', 'torrents_set_upload_limit', 'torrents_tags', 'torrents_toggleFirstLastPiecePrio', 'torrents_toggleSequentialDownload', 'torrents_toggle_first_last_piece_priority', 'torrents_toggle_sequential_download', 'torrents_topPrio', 'torrents_top_priority', 'torrents_trackers', 'torrents_uploadLimit', 'torrents_upload_limit', 'torrents_webseeds', 'transfer', 'transfer_banPeers', 'transfer_ban_peers', 'transfer_downloadLimit', 'transfer_download_limit', 'transfer_info', 'transfer_setDownloadLimit', 'transfer_setUploadLimit', 'transfer_set_download_limit', 'transfer_set_upload_limit', 'transfer_speedLimitsMode', 'transfer_speed_limits_mode', 'transfer_toggleSpeedLimitsMode', 'transfer_toggle_speed_limits_mode', 'transfer_uploadLimit', 'transfer_upload_limit']
>>>
```

### Steps to reproduce

Try to use qbitorrentapi.client.torrents_export function.

### Expected behavior

Should export the torrent.

### Environment

- Operating System: Arch linux
- Python version: 3.10.8
- Software versions:
  - qBittorrent: 4.5.4 
  - qbittorrent-api: 2023.6.50

**Comment by rmartin16** [comment]
Your expectation is correct.....however, it looks like I forgot to add `export()` to `Torrents`; it exists on `TorrentsAPIMixIn`, though.

If you try this instead, it should work for now:
```python
qbt_client.torrents_export(torrent_hashes={torrent.hash}, location='/config/.')
```

I should be able to fix this later today. Thanks for letting me know.

**Comment by sotiris-bos** [comment]
> Your expectation is correct.....however, it looks like I forgot to add `export()` to `Torrents`; it exists on `TorrentsAPIMixIn`, though.
> 
> If you try this instead, it should work for now:
> 
> ```python
> qbt_client.torrents_export(torrent_hashes={torrent.hash}, location='/config/.')
> ```
> 
> I should be able to fix this later today. Thanks for letting me know.

```
Traceback (most recent call last):
  File "/root/.scripts/qbit_final.py.test", line 36, in <module>
    qbt_client.torrents_export(torrent_hashes={torrent.hash}, location='/config/.')
AttributeError: 'Client' object has no attribute 'torrents_export'. Did you mean: 'torrents_info'?
```

It doesn't work with the underscore instead of the point but I get it that it is an easy fix so I am going to wait for it. Thank you for the rapid reply and thanks a lot for your work!

**Comment by rmartin16** [comment]
hmm....I know `torrents_export()` exists.

Can you confirm the installed version of `qbittorrent-api`? Simple `python -m pip list` should be enough.

**Comment by rmartin16** [comment]
As it relates to `Client.torrents.export()` being missing, this actually appears to be somewhat by design...

There are two different types of qBittorrent's API endpoints for torrents: those that act on a single torrent and those are act on one or more torrents.

It may not be immediately obvious which are which in this API client...but it can be inferred from whether the method accepts `torrent_hash` or `torrent_hashes`. For instance, [`torrents_set_download_limit()`](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_set_download_limit) is for multiple torrents while [`torrents_trackers()`](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_trackers) is for a single torrent.

The methods currently available from `Client.torrents` is only the methods that support multiple torrents; so, `Client.torrents.trackers()` isn't available either.

I think my intention was for the single-torrent API endpoints to be available from the actual torrent object, like this:
```python
for torrent in client.torrents.info():
     torrent.export()
```

I can't say I particularly understand that design decision at this point....although, that decision would have been made 5 or 6 years ago.

Nonetheless, if I add `export()` to `client.torrents`, I will need to add all the single torrents API endpoints...

**Comment by sotiris-bos** [comment]
> hmm....I know `torrents_export()` exists.
> 
> Can you confirm the installed version of `qbittorrent-api`? Simple `python -m pip list` should be enough.

Well, I had qbittorrent-api installed both by pip and from the AUR and Python was importing the pip version which was 2022.10.something. I removed the pip package, reinstalled from the AUR and I now got the proper version that has the export function.

Sorry for the fuss, the multiple torrent API endpoint is fine for my use case, so you can go ahead and close the issue.

Thank you for your time!

**Comment by sotiris-bos** [comment]
OK, I got the script running without errors like this:

```
for torrent in qbt_client.torrents_info():
        if torrent.state_enum.is_uploading or torrent.state_enum.is_complete: 
          if not torrent.properties.is_private:
                qbt_client.torrents_export(torrent_hash={torrent.hash}, location='/root/.')
          elif torrent.properties.is_private:
                qbt_client.torrents_export(torrent_hash={torrent.hash})
```

But I am not getting any .torrent files anywhere, neither in the /root/ folder nor in the current directory.

Any ideas how this is supposed to work?

**Comment by rmartin16** [comment]
`Client.torrents_export()` doesn't support a `location` argument and the `torrent_hash` should just be a `str`, not a `set` (as enclosing it in braces will do).

Nonetheless, `Client.torrents_export()` returns a bunch of bytes you can save to a file; for instance:
```python
with open("mytorrent.torrent", "wb") as file:
    file.write(client.torrents_export(torrent_hash="d905772b8e0d3a99d014f5046bccfd1e6d076885"))
```

That'll create a torrent file in the current directory with name `mytorrent.torrent`.

**Comment by sotiris-bos** [comment]
Perfect! Thank you for your help, I am a total python noob as you might have guessed.

I am using 3 different torrent clients. One is qbittorrent where everything gets downloaded, then I have two transmission torrent clients for seeding, one for public, one for private torrents. I wanted to use qbittorrent to download torrents because it is faster, but I like transmission because I am more used to it.

Having a public and private torrent client allows me to set different ratios/bandwidth limits etc for public and private torrents. I wanted to implement a script that would be run by cron that would differentiate between the public and private torrents on qbittorrent and export their .torrent files to their respective transmission client. This script can be used with any second/third torrent client that has a watched folder location.

Here is my full python script:

```
import qbittorrentapi

#This script is used with 3 torrent clients. One is the main qbittorrent client where everything is downloaded, then torrents are separated to public and private and their .torrent files are exported to a second and a third torrent client, one used for public torrents and one used for private. After the .torrent files have been created to the respective "watched" directory of each client, they are deleted from the first qbittorrent client. Thus, the first qbittorrent client has no torrents active, while the second and third can continue seeding the already downloaded torrents, with different speed and peer settings depending on if they are seeding public or private torrents. I use cron for running this python script once a day.

# instantiate a Client using the appropriate WebUI configuration
qbt_client = qbittorrentapi.Client(
    host='_YOUR QBITTORRENT IP OR HOSTNAME HERE_',
    port=8080,
    username='_YOUR QBITTORRENT USERNAME HERE_',
    password='_YOUR QBITTORRENT PASSWORD HERE_'
 )

#Find completed/uploading public and private torrents and export their .torrent files to their respective location to be picked up by the "public" or "private" torrent client.
for torrent in qbt_client.torrents_info():
        if torrent.state_enum.is_uploading or torrent.state_enum.is_complete: 
          if not torrent.properties.is_private:
              with open(f'/mnt/media/torrents/watched/{torrent.name}.torrent', "wb") as file:  #change /mnt/media/torrents/watched/  to your second (public) torrent client's watched folder
               file.write(qbt_client.torrents_export(torrent_hash={torrent.hash}))
               qbt_client.torrents_delete(torrent_hashes={torrent.hash})
          elif torrent.properties.is_private:
              with open(f'/mnt/media/torrents/private_watched/{torrent.name}.torrent', "wb") as file:  #change /mnt/edia/torrents/watched/  to your third (private) torrent client's watched folder
               file.write(qbt_client.torrents_export(torrent_hash={torrent.hash}))
               qbt_client.torrents_delete(torrent_hashes={torrent.hash})
```

Thanks again for your time, your work and your help!

**Comment by ahopelesshadow** [comment]
is it possible to define a source or announce url while using torrents_export?

**Comment by rmartin16** [comment]
> is it possible to define a source or announce url while using torrents_export?

The `torrents/export` endpoint [only accepts](https://github.com/qbittorrent/qBittorrent/blob/488464731d1271f2ecd435beb3c956e7a1958bc5/src/webui/api/torrentscontroller.cpp#L1412) a torrent hash to control its behavior; however, that obviously just controls which existing torrent is used to create the torrent file.

The qBittorrent team would need to expose more configuration options to do something like this...but I'm doubting they would be particularly amenable to that.

Alternatively, something like [torf](https://pypi.org/project/torf/) appears like it would let you load and rewrite the torrent file after the fact.

**Comment by ahopelesshadow** [comment]
> 

yea im sort of looking at that now, i used torf in the past, and its rather slow...  but im wondering if i converted the bytes to str and then replaced the existing announce url then converted back to bytes if that would basically do it... so sorta hack the return i get from torrents_export.

**Comment by ahopelesshadow** [comment]
> > is it possible to define a source or announce url while using torrents_export?
> 
> The `torrents/export` endpoint [only accepts](https://github.com/qbittorrent/qBittorrent/blob/488464731d1271f2ecd435beb3c956e7a1958bc5/src/webui/api/torrentscontroller.cpp#L1412) a torrent hash to control its behavior; however, that obviously just controls which existing torrent is used to create the torrent file.
> 
> The qBittorrent team would need to expose more configuration options to do something like this...but I'm doubting they would be particularly amenable to that.
> 
> Alternatively, something like [torf](https://pypi.org/project/torf/) appears like it would let you load and rewrite the torrent file after the fact.

yea im sort of looking at that now, i used torf in the past, and its rather slow... but im wondering if i converted the bytes to str and then replaced the existing announce url then converted back to bytes if that would basically do it... so sorta hack the return i get from torrents_export.

as far as the qbit team not wanting go, i would see that as a 50/50 because in theory you can do that by creating a new torrent in the UI.  this is the next best thing i guess and not 100% the same but would result in the same output.


and..... so strike everything i just said, because the infohash should be different also... ok onto plan b.

**Comment by rmartin16** [comment]
> if i converted the bytes to str and then replaced the existing announce url then converted back to bytes if that would basically do it... so sorta hack the return i get from torrents_export.

I wouldn't try to reinvent the wheel. `torf` looks simple enough.

```python
import io

import qbittorrentapi
import torf

client = qbittorrentapi.Client(...)

torrent = torf.Torrent.read_stream(io.BytesIO(client.torrents_export("d905772b8e0d3a99d014f5046bccfd1e6d076885")))

torrent.trackers = ["my-tracker.com"]

torrent.write("mytorrent.torrent")
```
