### ISSUE TITLE
TorrentDictionary.properties raises AttributeError

### ISSUE THREAD

**Issue by jcassette** [rmartin16/qbittorrent-api#406]
### Describe the bug

See below

### Steps to reproduce
```
>>> qbittorrent = qbittorrentapi.Client(host=QB_HOST, port=QB_PORT, username=QB_USERNAME, password=QB_PASSWORD)
>>> qbittorrent.auth_log_in()
>>> torrents = qbittorrent.torrents_info()
>>> print(torrents[0].properties)
TorrentPropertiesDictionary(...)
>>> torrents = qbittorrent.torrents_info()[0:1]
>>> print(torrents[0].properties)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/julien/qbittorrent/lib64/python3.12/site-packages/qbittorrentapi/_attrdict.py", line 146, in __getattr__
    raise AttributeError(
AttributeError: 'TorrentDictionary' instance has no attribute 'properties'
```
### Expected behavior
```
>>> qbittorrent = qbittorrentapi.Client(host=QB_HOST, port=QB_PORT, username=QB_USERNAME, password=QB_PASSWORD)
>>> qbittorrent.auth_log_in()
>>> torrents = qbittorrent.torrents_info()
>>> print(torrents[0].properties)
TorrentPropertiesDictionary(...)
>>> torrents = qbittorrent.torrents_info()[0:1]
>>> print(torrents[0].properties)
TorrentPropertiesDictionary(...)
```

### Environment

- Operating System: Fedora Linux 39
- Python version: 3.12.1
- Software versions:
  - qBittorrent: 4.5.4
  - qbittorrent-api: 2024.1.58

**Comment by rmartin16** [comment]
I can replicate this behavior and it is almost certainly related to the list slicing. Unfortunately, slicing can create wholly new objects and has had unfortunate side effects [before](https://github.com/rmartin16/qbittorrent-api/pull/228) in this library.

I haven't determined the root causes specifically here yet...but slicing, in general, seems to be problematic for this implementation...
