### ISSUE TITLE
RecursionError on Login Retry: Infinite Retry Loop with Invalid Credentials

### ISSUE THREAD

**Issue by InfinityPacer** [rmartin16/qbittorrent-api#500]
### Describe the bug

When using an incorrect username or password to log in, the SDK automatically retries the login multiple times. After several failed attempts, the server bans the IP due to excessive login failures. This eventually leads to a recursion error (RecursionError: maximum recursion depth exceeded), causing the system to enter an infinite loop.

### Steps to reproduce

1. Attempt to log in with an incorrect username/password combination.
2. The SDK will automatically retry the login.
3. After multiple retries, the server bans the IP due to excessive failed login attempts.
4. This triggers a recursion depth error, causing the system to enter an infinite loop.

### Expected behavior

The sdk should stop retrying after a certain number of failed attempts and provide a meaningful error message, rather than attempting an infinite number of retries and resulting in a recursion error.

### Environment

- Operating System: Windows 11
- Python version: 3.11
- Software versions:
  - qBittorrent: 5.0
  - qbittorrent-api: 2024.9.67

### Additional context

```python
    def __login_qbittorrent(self) -> Optional[Client]:
        """
        连接qbittorrent
        :return: qbittorrent对象
        """
        try:
            # 登录
            logger.info(f"正在连接 qbittorrent：{self._host}:{self._port}")
            qbt = qbittorrentapi.Client(host=self._host,
                                        port=self._port,
                                        username=self._username,
                                        password=self._password,
                                        VERIFY_WEBUI_CERTIFICATE=False,
                                        REQUESTS_ARGS={'timeout': (15, 60)})
            try:
                sys.setrecursionlimit(100)
                qbt.auth_log_in()
            except (qbittorrentapi.LoginFailed, qbittorrentapi.Forbidden403Error) as e:
                logger.error(f"qbittorrent 登录失败：{str(e)}")
                return None
            except Exception as e:
                logger.error(f"qbittorrent 登录失败：{str(e)}", exc_info=True)
                return None
            return qbt
        except Exception as err:
            logger.error(f"qbittorrent 连接出错：{str(err)}")
            return None
```

```log
INFO:    2024-11-14 17:39:40,884 qbittorrent.py - 正在连接 qbittorrent：http://<hidden>:<hidden>
ERROR:   2024-11-14 17:39:41,058 qbittorrent.py - qbittorrent 登录失败：Failed to connect to qBittorrent. Unknown Error: RecursionError('maximum recursion depth exceeded')
Traceback (most recent call last):
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 591, in _auth_request
    return self._request_manager(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 664, in _request_manager
    return self._request(
           ^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 816, in _request
    self._handle_error_responses(final_data, final_params, response)
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 991, in _handle_error_responses
    raise Forbidden403Error(response.text, request=request, response=response)
qbittorrentapi.exceptions.Forbidden403Error: 身份认证失败次数过多，您的 IP 地址已被封禁。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 591, in _auth_request
    return self._request_manager(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 664, in _request_manager
    return self._request(
           ^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 816, in _request
    self._handle_error_responses(final_data, final_params, response)
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 991, in _handle_error_responses
    raise Forbidden403Error(response.text, request=request, response=response)
qbittorrentapi.exceptions.Forbidden403Error: 身份认证失败次数过多，您的 IP 地址已被封禁。

...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 664, in _request_manager
    return self._request(
           ^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 799, in _request
    url = self._url.build(api_namespace, api_method, headers, requests_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 90, in build
    self.build_base_url(headers or {}, requests_kwargs or {}),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 141, in build_base_url
    scheme = self.detect_scheme(
             ^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 188, in detect_scheme
    r = self.client._session.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 227, in request
    return super().request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 344, in begin
    self.headers = self.msg = parse_headers(self.fp)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 243, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\feedparser.py", line 174, in feed
    self._call_parse()
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\feedparser.py", line 178, in _call_parse
    self._parse()
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\feedparser.py", line 254, in _parsegen
    if self._cur.get_content_type() == 'message/delivery-status':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\message.py", line 606, in get_content_type
    value = self.get('content-type', missing)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\message.py", line 499, in get
    return self.policy.header_fetch_parse(k, v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\AppData\Local\Programs\Python\Python311\Lib\email\_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<hidden>\app\modules\qbittorrent\qbittorrent.py", line 80, in __login_qbittorrent
    qbt.auth_log_in()
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 608, in _auth_request
    self.auth_log_in(  # type: ignore[attr-defined]
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\auth.py", line 88, in auth_log_in
    auth_response = self._post_cast(
                    ^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 555, in _post_cast
    self._auth_request(
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 591, in _auth_request
    return self._request_manager(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "<hidden>\venv\Lib\site-packages\qbittorrentapi\request.py", line 705, in _request_manager
    raise APIConnectionError(err_msg, response=response)
qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Unknown Error: RecursionError('maximum recursion depth exceeded')
```

**Comment by rmartin16** [comment]
Thanks for letting me know. Looks like this issue only affects the `auth_log_in()` call; in `Request._auth_request()`, I just need to immediately `raise` when catching a `HTTP403Error` for a call to the `auth/login` endpoint. I imagine I introduced this in a relatively recent refactor of how authentication mgmt was being handled.

**Comment by InfinityPacer** [comment]
Yes, even without explicitly calling `auth_log_in`, the login requests initiated by the SDK are facing similar issues. thanks a lot.

**Comment by rmartin16** [comment]
Ahhh, ok; so, it's only once you're banned. That explains why my tests didn't catch this. Thanks. I should be able to release a fix this weekend.
