### ISSUE TITLE
Unterminated string starting at

### ISSUE THREAD

**Issue by swannie-eire** [rmartin16/qbittorrent-api#83]
Im getting a strange error. Im currently using [seedcross](https://github.com/ccf-2012/seedcross) and get this error with your API. Im unsure of why.  

here is the traceback.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 161, in wrapper
    result = response.json()
  File "/root/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 239700 (char 239699)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/root/seedcross/crseed/tasks.py", line 80, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/root/seedcross/crseed/CrossSeedAutoDL.py", line 356, in iterTorrents
    torList = dlclient.loadTorrents()
  File "/root/seedcross/crseed/torclient.py", line 196, in loadTorrents
    torList = self.qbClient.torrents_info()
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 112, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 170, in wrapper
    raise APIError("Exception during response parsing. Error: %r" % exc)
qbittorrentapi.exceptions.APIError: Exception during response parsing. Error: JSONDecodeError('Unterminated string starting at: line 1 column 239700 (char 239699)')

```

Any idea what the cause could be?

**Comment by rmartin16** [comment]
And I guess seeing how it may be non-trivial to update a local copy of `seedcross` to enable additional logging and run that updated code, it may be a better just to create an independent python virtual environment, install `qbittorrent-api` and test if the same thing happens. This may help isolate the problem more easily. I could help walk through any of that as well if you'd like.

**Comment by rmartin16** [comment]
Finally, as far as speculation about potential root causes....I'd guess that JSON isn't being returned at all....or qBittorrent is returning invalid JSON.

JSON may not be returned at all if an intervening proxy (or something else) is replacing the content from qBittorrent; such as with an HTML document....maybe for captive network log on. Although, I'd expect the JSON parser to error sooner since the first character of an HTML document is invalid JSON.

Alternatively, and perhaps even more likely.....qBittorrent is building invalid JSON.....maybe because of special characters within the metadata of the one or more of the torrents. Of note, for this client to even make the `torrents_info` API call, it first needed to successfully log in; so, I think that makes my first guess above much less likely since communication with qBittorrent to log in is apparently possible.

**Comment by swannie-eire** [comment]
first off thanks for the super fast response.

So i did what you suggested in your first comment and added the below to where qbClient is instantiated but the logs i get are pretty much the same.

```
import logging
logging.basicConfig(level=logging.DEBUG, format='[%(asctime)s] {%(name)s:%(lineno)d} %(levelname)s - %(message)s')

import qbittorrentapi
qbClient = qbittorrentapi.Client(host='localhost:8080', username='admin', password='adminadmin', VERBOSE_RESPONSE_LOGGING=True)
```

**logs**
```
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 161, in wrapper
    result = response.json()
  File "/root/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 241688 (char 241687)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/root/seedcross/crseed/tasks.py", line 80, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/root/seedcross/crseed/CrossSeedAutoDL.py", line 356, in iterTorrents
    torList = dlclient.loadTorrents()
  File "/root/seedcross/crseed/torclient.py", line 200, in loadTorrents
    torList = self.qbClient.torrents_info()
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 112, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 170, in wrapper
    raise APIError("Exception during response parsing. Error: %r" % exc)
qbittorrentapi.exceptions.APIError: Exception during response parsing. Error: JSONDecodeError("Expecting ',' delimiter: line 1 column 241688 (char 241687)")
Marking task proceed_cross_seed as failed
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 161, in wrapper
    result = response.json()
  File "/root/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 241688 (char 241687)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/root/seedcross/crseed/tasks.py", line 80, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/root/seedcross/crseed/CrossSeedAutoDL.py", line 356, in iterTorrents
    torList = dlclient.loadTorrents()
  File "/root/seedcross/crseed/torclient.py", line 200, in loadTorrents
    torList = self.qbClient.torrents_info()
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 112, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/qbittorrentapi/decorators.py", line 170, in wrapper
    raise APIError("Exception during response parsing. Error: %r" % exc)
qbittorrentapi.exceptions.APIError: Exception during response parsing. Error: JSONDecodeError("Expecting ',' delimiter: line 1 column 241688 (char 241687)")
Marking task proceed_cross_seed as failed
```

to test on a independent python virtual environment i assume i can just spin up a docker container and install qbittorrent-api? If so is there certain commands or script i should run.

There is no proxy between the seedcross server and the qbittorrent server as both are on the same LAN. The qbit server does connect to the internet via a VPN but that should not have any relevance here as the connection between seedcross server and the qbittorrent server is a LAN.

I agree with you about the possible cause being special characters within the metadata. That was my first guess too as i have a few torrents that have special chars in the names or Chinese name etc.. and since the problem occurs at different times and does not provide which torrent is the issue its hard for me to identify the root cause without removing 100+ torrents with Chinese chars or spacial chars one by one and running seedcross after each one.

**Comment by swannie-eire** [comment]
sorry about the delay been a busy week or so. 

I ran both commands you provided and didnt get the error with either.

I would of expected to get an error for client.torrents_info() and then an error when the loop hit the issue torrent.

Any other suggestions. I may be missing the error with the loop as the output is huge and i have to watch it to see which one errors. Is there a way with the loop to just print the torrents that caused exceptions or errors?

**Comment by rmartin16** [comment]
hmm.....interesting. That suggests the problem is likely intermittent.....and as such makes it much harder to track down. Additionally, the dictionary for each torrent that is returned from `client.torrents_info()` do not contain much dynamic content other than changing statistics; so, that does make me wonder if special characters could really be the root cause given I wouldn't expect them to be appearing and disappearing in this payload....

Nonetheless, another option is just to run `client.torrents_info()` in an infinite loop:

```python
from time import sleep
import logging
import qbittorrentapi

logging.basicConfig(level=logging.DEBUG, format='[%(asctime)s] {%(name)s:%(lineno)d} %(levelname)s - %(message)s')
client = qbittorrentapi.Client(host='localhost:8080', username='admin', password='adminadmin', VERBOSE_RESPONSE_LOGGING=True)
LOOP_INTERVAL = 3  # seconds

while True:
    for idx in range(len(client.sync.maindata()['torrents'])):
        print(client.torrents_info(limit=1, offset=idx))
    sleep(LOOP_INTERVAL)
```

You can change `LOOP_INTERVAL` to have it run as often as you like. And the loops will break out as soon as there's a problem; so, no need to watch it. The exception will be the last thing printed once one occurs.

**Comment by swannie-eire** [comment]
so i had that script running for over 24 hours and have not seen the issue once.

I also have not replicated the issue with seedcross. I have a feeling that the issue is that when i first run seedcross it overloads the qbittorrent instances as so many new torrents are being added and being rechecked and thats the cause of the Unterminated string since the qbit is so overloaded.

i think its best to close this for now and Ill reopen if i can re-produce.

BTW thanks for the prompt responses and the excellent help.
